#!/bin/sh
yr=1986
while [ $yr -le 1995 ]
do
  cp gswp/cable.nml_${yr} cable.nml
  cable
  mv out_cable.nc      out_gswp/out_cable_gswp${yr}.nc
  mv log_cable.txt     out_gswp/log_cable_gswp${yr}.txt
  cp -p restart_out.nc out_gswp/restart_out_gswp${yr}.nc
  mv restart_out.nc    restart_in_gswp.nc
  yr=`expr $yr + 1`
done

