c $Log: linear.f,v $
c Revision 1.9  1996/10/24 01:02:59  ldr
c Comments, Legendre transforms and tidy-ups from TIE
c
c Revision 1.8  1993/12/06  16:55:29  ldr
c Changes to V4-4-45l to get T63 running on SGI (Seca).
c
c Revision 1.7  93/10/05  13:06:35  ldr
c Changes to V4-4-15l from HBG for T63 and coupled model
c 
c Revision 1.6  93/07/14  14:54:56  ldr
c The linear terms generated by P*f are now included in the nonlinear terms
c (ready for implicit vorticity)(HBG).
c 
c Revision 1.5  93/07/06  16:17:47  ldr
c      Added small extension array to common block elmuv
c      (for overshoot in ptogcray). Added code at end of uvharm.f to set zero
c 
c Revision 1.4  92/12/09  14:43:48  ldr
c Replaced all n's with nl's for compatibility with ogcm.
c 
c Revision 1.3  92/04/22  11:46:34  ldr
c Put /fldri in include file.
c 
c Revision 1.2  91/03/13  12:58:53  ldr
c Common blocks put into include file form.
c Any changes made since V3-0 and this V3-1 merged.
c 
c Revision 1.1  91/02/22  16:37:36  ldr
c Initial release V3-0
c
c     INPUT/OUTPUT:
c     Input:   from common/cnste in CNSTE.f
c                  flm2 - l(l+1) part of spectral form
c
c 
C$MP_SCHEDTYPE=INTERLEAVE

      subroutine linear
      include 'PARAMS.f'
      include 'CNSTE.f'
      include 'WORKRID.f'
      include 'LLMAX.f'

C**** TO ADD LINEAR TENDANCIES
      do 130 k=1,nl
      do 130 mm=1,mw
      do 130 ll=1,llmax(mm)
      ixr(ll,mm,k)=ixr(ll,mm,k)+flm2(ll,mm)*elr(ll,mm,k)
      ixi(ll,mm,k)=ixi(ll,mm,k)+flm2(ll,mm)*eli(ll,mm,k)
  130 continue
C****
      do 179 k=1,nl
      ipr(1,1,k)=0.0
      ipi(1,1,k)=0.0
      ixr(1,1,k)=0.0
  179 ixi(1,1,k)=0.0
      return
      end
